language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS="--prefer-stable"

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - composer validate --strict
  - travis_retry composer self-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit

branches:
  only:
    - master
    - develop

notifications:
  email:
    on_failure: change
    on_success: never
